version: "3"
services:
  server:
    image: yandex/clickhouse-server
    expose:
      - "5432"
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  client:
    expose:
      - "5432"
    image: yandex/clickhouse-client
    command: ['--host', 'server']
