dbt_shop:
    outputs:
        dev:
            type: postgres
            threads: 2
            host: localhost
            port: 5433
            user: postgres
            pass: postgres
            dbname: postgres
            schema: dbt
    target: dev